### ISSUE TITLE
Build feild MethodCallHandlerImpl.kt: (45, 84): Unresolved reference: R

### ISSUE THREAD

**Issue by skylning** [moovida/smash#104]
I build the newest smash code ,and get the message:
....\fluttertoast-7.1.8\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (45, 84): Unresolved reference: R

and i found the error code is :
 if (bgcolor != null && Build.VERSION.SDK_INT < Build.VERSION_CODES.R) 

 when the compileSdkVersion is 30, Build.VERSION_CODES.R is right,but the smash project compileSdkVersion is 29,if change the smash project compileSdkVersion  to 30,other error occur,how to solve it?

**Comment by moovida** [comment]
How are you building? What ide? What gradle version? What flutter version?

**Comment by skylning** [comment]
IDE:AS 4.1.2
gradle:4.1.2
flutter:1.22.5

and i replace  Build.VERSION_CODES.R  as 30,it works,
![image](https://user-images.githubusercontent.com/3397551/108823003-d160fc00-75fa-11eb-9ba3-738572b46dfe.png)

**Comment by moovida** [comment]
I think basing on version 30 at the moment is not possible with flutter, since it would not allow to use the legacy filesystem. 

I am using vscode as ide, so I am not sure if there is something that Androidstudio is doing in background on the android project.

**Comment by moovida** [comment]
Good news, I got the same issue and committed a fix. Can you please try it out?

**Comment by skylning** [comment]
i tested it and works fine,thanks
