### ISSUE TITLE
Support label and value as "stringcombo" item

### ISSUE THREAD

**Issue by sanak** [moovida/smash#107]
@moovida (CC: @dkastl, @mbasa-georepublic)
Currently, "stringcombo" - "values"/"items" - each "item" accepts only `string` expression,
https://www.geopaparazzi.org/geopaparazzi/#_combos
```dart
"formitems": [
    {
        "key": "a single choice combo",
        "values": {
            "items": [
                {"item": ""},
                {"item": "choice 1"},
                {"item": "choice 2"},
                {"item": "choice 3"},
                {"item": "choice 4"},
                {"item": "choice 5"}
            ]
        },
        "value": "",
        "type": "stringcombo"
    }
```

but in some cases (like our Redmine integration trial), supporting `label` and `value` format (below No.2) is quite important.
(This is like HTML `select/option` - `Node text`/`value` (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select)).

1. Current pattern
   ```dart
   {"item": "choice 1"},
   ```
   Selected value => `choice 1`
2. Additional `label` and `value` support pattern 
   ```dart
   {"item": {"label": "choice 1", "value": "1"}},
   ```
   Selected value => `1`

I am not sure how difficult to support both No.1 and No.2 with Dart/Flutter, but supporting this enhancement is quite helpful for us.

**Comment by sanak** [comment]
@moovida (CC: @dkastl, @mbasa-georepublic)  
I just made the following Pull Request to `smashlib` side, so reviewing this is quite helpful.
- https://github.com/moovida/smashlibs/pull/1

**Comment by moovida** [comment]
Hi @sanak , that was fast :-) 
I will comment on the smashlibs PR. Thanks.
