### ISSUE TITLE
Draw a polyline and polygon featrues

### ISSUE THREAD

**Issue by skylning** [moovida/smash#11]
the project can draw a polyline or polygon notes?

**Comment by moovida** [comment]
Hi @skylning , no at the current time geometry editing is not supported yet.
The current steps are:

* editing of alphanumeric in attributes tables (of vector geopackage files)
* editing of geometries in vector tables

But we do not have a timeline yet, we are currently looking for funds to back the work.

Obviously PR are most welcome :-)

**Comment by skylning** [comment]
I expect it so much

**Comment by moovida** [comment]
@skylning , we started working on this part. But it will take some time. But it should be in the next release... fingers crossed.

**Comment by skylning** [comment]
It's a great job,thanks!

**Comment by moovida** [comment]
This is now done

**Comment by shujaatak** [comment]
@moovida can you please describe how can we add lines or polylines to the map? When I add a line, the app show warning and does not allow me to add it to the map.

**Comment by moovida** [comment]
Hi, this is described here: https://www.geopaparazzi.org/smash/index.html#_feature_editing
If something doesn't work, please open a new issue and describe exactly what is happening. Sure you will need an editable layer to be available. But well, ideally it should warn you about that.

**Comment by shujaatak** [comment]
Thank you so much for the response.  Well I read the documentation and searched internet for geopackaged vector maps but none of them allow me to add/edit features. Can you please share a sample editable map so that I may get started?

As I think, it's not a bug or something that's why I am reluctant to post new issue.
