### ISSUE TITLE
Form text note Japanese input (with IME) doesn't work correctly on Android

### ISSUE THREAD

**Issue by sanak** [moovida/smash#111]
Simple note was no problem on both Japanese Kana and Romaji input.
![Screenshot_20210323-002700](https://user-images.githubusercontent.com/629923/112015650-5a724100-8b6f-11eb-9fe9-08591dfe3718.jpg) ![Screenshot_20210323-002647](https://user-images.githubusercontent.com/629923/112015677-5fcf8b80-8b6f-11eb-80f4-c0a6ab60fcc0.jpg)

But, Form text note Japanese input doesn't work on both Kana and Romaji input.
![Screenshot_20210323-002542](https://user-images.githubusercontent.com/629923/112015711-6827c680-8b6f-11eb-87f7-8845c82396a2.jpg) ![Screenshot_20210323-002741](https://user-images.githubusercontent.com/629923/112015727-6b22b700-8b6f-11eb-87ad-5776f1372c60.jpg)

I felt that the cursor seems to keep left end position during IME input on form text note.

Above was reproducible on the latest `master` branch, but I couldn't check it on iOS.
App Store released iOS app (1.16.4) was no problem on both simple note and form text note.

**Comment by moovida** [comment]
This should be solved with you PR @sanak 
Closing it here. Thanks!
