### ISSUE TITLE
Unable to install latest Android build smash_1.0.0+2.apk

### ISSUE THREAD

**Issue by AndrewM-** [moovida/smash#20]
My phone says that the apk file is corrupt.  I downloaded it twice with the same result.

**Comment by moovida** [comment]
Hi @AndrewM- thanks for pointing out. I will do a new build later today and test it. I will keep you posted.

**Comment by AndrewM-** [comment]
I could install 1.1 only after uninstalling the previous version.  Then things installed without issue.  A screenshot of the error message is below.
![Screenshot_20200520-110714 1](https://user-images.githubusercontent.com/5060805/82396403-2763aa80-9a91-11ea-80b1-0a4c0976b0b9.jpg)

**Comment by moovida** [comment]
Hi @AndrewM- , this might be due to the fact that the previous was installed from the store? In that case the signature would be different and android doesn't allow over-installing.

**Comment by AndrewM-** [comment]
@moovida I have purchased an iphone and can confirm that 1.2.1 works fine.
