### ISSUE TITLE
smash Latest version startup error?

### ISSUE THREAD

**Issue by sakuya-izayoi-0518** [moovida/smash#32]
Thank you for your help.
I installed the latest version of the application on google play.
It has started.
I cannot go beyond the screen of the attached image.
Android version is 8.
Smash Ver0.1.0 works without problems.
![start up](https://user-images.githubusercontent.com/55145028/83224468-6c39c080-a1b8-11ea-9931-5726c4eef321.png)

**Comment by moovida** [comment]
Hi @sakuya-izayoi-0518 , sadly I do not own an android 8 device, so I will have to ask you some input.

* before upgrading did you have version 1.2.0 installed, right. It wasn't an installation from scratch
* on the device, inside the **smash/config/** folder, is there a gp_debug.sqlite file? In case could you send it to me?
* can you try to force stop the application, then backup the folder **smash** on your device and remove the folder and then restart it?

**Comment by sakuya-izayoi-0518** [comment]
Thank you for raction.
Smash Ver0.1.0 was uninstalled before Smash Ver 1.2.0 installed.

Sorry, I can't find [smash / config / folder] in my terminal.
So,I cannot send you gp_debug.sqlite file.

I tried to force stop the application, and I was restart this applocation.
But same resalt. I can't find [smash / config / folder] in my terminal. 
( I can find [eu.hydrologis.smash / files / pictures ]. But this folder is empty.)

I'm sorry I can't help you.

**Comment by sakuya-izayoi-0518** [comment]
Hello author
After installing SMASH several times, the map can be displayed.
I took care of you.

**Comment by moovida** [comment]
Thank you @sakuya-izayoi-0518 
Great to hear it has solved itself. Sorry I could not be of help.
Feel free to write if there are other issues.
