### ISSUE TITLE
Is it possible to access the SD card with SMASH?

### ISSUE THREAD

**Issue by sakuya-izayoi-0518** [moovida/smash#34]
Is it possible to access the SD card with SMASH?
I have an android smartphone.

And
Is it possible to move to the center of the background mbtile in SMASH? (Like Geopaparazzi)

**Comment by sakuya-izayoi-0518** [comment]
sorry. I can move to the center by swiping the layer to the left.

**Comment by moovida** [comment]
Hi @sakuya-izayoi-0518 , good to hear the zoom to layer works for you.

About the SDCARD, I assume you mean the external sdcard. Recently android made it difficult as in IOS to access the filesystem: https://www.xda-developers.com/android-q-storage-access-framework-scoped-storage/

So basically it is a lot of work to make this work properly and being a voluntary project, this is currently not a priority... and given the price it won't be in future.

So we are only supporting internal sdcard access.
