### ISSUE TITLE
Right drawer: missing "Map Plugins" menu 

### ISSUE THREAD

**Issue by colla70** [moovida/smash#51]
SMASH 1.3.0
Samsung Galaxy A40
Android 10

![Screenshot_20200730-132215](https://user-images.githubusercontent.com/13482593/88917978-fd84ec00-d268-11ea-80c3-38040f23541a.jpg)

**Comment by moovida** [comment]
Hi, the plugins have been moved on double tap of the layer button to follow a common semantic of faster accessibility.

Double tap on the layer button and you will get the plugins dialog.

Feel free to reopen if you have issues.
