### ISSUE TITLE
Overlap between measure and log info 

### ISSUE THREAD

**Issue by silviafranceschi** [moovida/smash#60]
When logging there are some information about the distance and time written on a box on the top right of the window. 
If you use the measuring tool while logging the information about the length of the drawing line will be displayed in the same position of the information about the logging resulting in an overlapping of information.
I propose to not to display the information about the logging while the measuring tool is active. 
An other solution could be to display the measuring information  in an other position on the map, but could be an option to display the value in the toolbar over the measuring tool like the number of notes and logs with their respective icons?

**Comment by moovida** [comment]
Moved measurement text into badge of icon as suggested.
