### ISSUE TITLE
Error while saving a picture in form note (image note)

### ISSUE THREAD

**Issue by silviafranceschi** [moovida/smash#63]
The program register pictures regularly if I take a simple note (picture) but if I use a form and try to add a picture, the error reported is "Could not save image to database".
![IMG_0883](https://user-images.githubusercontent.com/7670552/93871301-b64a3300-fcce-11ea-8efb-3e7b87a02e7d.PNG)

**Comment by moovida** [comment]
Do you see something in the debug log? Any error?
I will look into this first thing afternoon.

**Comment by silviafranceschi** [comment]
Attached there is the screenshot, sorry I can not understand myself where is the problem.

![IMG_0884](https://user-images.githubusercontent.com/7670552/93879604-4478e600-fcdc-11ea-8b87-adc62f10a6c0.PNG)

**Comment by moovida** [comment]
No problem, will have to reproduce it to understand.

**Comment by moovida** [comment]
Found the issue. It is now fixed. Will do a new testflight.
