### ISSUE TITLE
Select rasters to open from Geopackage

### ISSUE THREAD

**Issue by ddotzov** [moovida/smash#74]
When a Geopackage contains more than one raster, select which ones to open. Currently upon opening a Geopackage there is option to select which vector layers should be opened, but not for rasters. So by default all raster from the geopackage are loaded. Can you please add the option to also choose individual rasters to open.

**Comment by moovida** [comment]
Good timing @ddotzov , I am making last fixes for the new release and I had forgotten about this. Will add it.

**Comment by moovida** [comment]
You do not happen to have one to share with several layers? I have limited time and would have to create one :-)

**Comment by moovida** [comment]
Forget the above @ddotzov , I found one (also supplied by you :-) ) and actually I found a bug for which it was not loading the bounds in case of special table names. So that one is also fixed. 

This is going in the next release.
