### ISSUE TITLE
Abnormal GPS behavior on iPhone XS

### ISSUE THREAD

**Issue by silviafranceschi** [moovida/smash#76]
Testing done only on GPS position without fencing and taking notes.
1. if the automatic center on GPS is not active
	- with track log active and screen on: the GPS icon moves according to the movement of the device → ok!
	- without track log and with the screen on: the GPS icon do not move from the last “center on GPS” position
	- without track log and with the screen off: the GPS icon do not move from the last “center on GPS” position, when you unlock the phone and access the application the GPS icon will automatically positioned in the new correct position together with the map as a Center on GPS operation is done

2.  if the automatic center on GPS is active
	- with track log active and screen on: the GPS icon moves according to the movement of the device → ok!
	- without track log and with the screen on: the GPS icon moves according to the movement of the device and the map center is correctly shifted with the GPS position → ok!
	- without track log and with the screen off: the GPS icon do not move from the last “center on GPS” position, when you unlock the phone and access the application the GPS icon will automatically positioned in the new correct position together with the map as a Center → ok!

**Comment by moovida** [comment]
This has been finally fixed. Sending out a test version.

**Comment by silviafranceschi** [comment]
I tried the last Testflight version 1.6.1 on iphone XS and realized that if I kill the application while the GPS signal is fine (green bullet) then, when I restart the application I can not switch off my GPS anymore.
