### ISSUE TITLE
Problem opening the documentation

### ISSUE THREAD

**Issue by silviafranceschi** [moovida/smash#83]
On my iphone XS OFFLINE I had this error, if I am ONLINE, the application opens directly the browser with the link of the documentation:
Error:
PlatformException(Error, Error while launching http://www.geopaparazzi.org/smash/index.html, null, null)

Stack trace:
#0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
#1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)

#2 launch (package:url_launcher/url_launcher.dart:95)

#3 DashboardUtils.getDrawerTilesList. (package:smash/eu/hydrologis/smash/mainview_utils.dart:175)

Device parameters:
model: iPhone
isPhysicalDevice: true
name: HyiPhoneXS
identifierForVendor: C0407000-3E4E-4237-A88F-F5F505CE66B7
localizedModel: iPhone
systemName: iOS
utsnameVersion: Darwin Kernel Version 20.0.0: Wed Sep 30 03:24:41 PDT 2020; root:xnu-7195.0.46~41/RELEASE_ARM64_T8020
utsnameRelease: 20.0.0
utsnameMachine: iPhone11,2
utsnameNodename: HyiPhoneXS
utsnameSysname: Darwin

Application parameters:
environment: release
version: 1.6.1
appName: null
buildNumber: 48
packageName: eu.hydrologis.smash

**Comment by moovida** [comment]
fixed
