### ISSUE TITLE
Export to PDF not surport Unicode string

### ISSUE THREAD

**Issue by skylning** [moovida/smash#85]
Thanks  moovida hard work for the great project,i test it and encounted the issue as follow: 

I/flutter (23024): Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter (23024): Helvetica-Bold has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter (23024): ---------------------------------------------
I/flutter (23024): Cannot decode the string to Latin1.
I/flutter (23024): This font does not support Unicode characters.
I/flutter (23024): If you want to use strings other than Latin strings, use a TrueType (TTF) font instead.
I/flutter (23024): See https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter (23024): ---------------------------------------------

**Comment by moovida** [comment]
Hi @skylning , the unicode support is something we will take care of at some point, but right now we have the resources to do so.

If you are able to contribute some fix to enable the use of TTF, that would be awesome.

**Comment by skylning** [comment]
i fixed the issue by myself as follow :
1.add my font to pubspecal.yaml and copy my font to assets path:
    - assets/xx.ttf

 2.define my theme and set document objects theme in pdf_export.dart as follow:
 
var myTheme = Theme.withFont(
      base: Font.ttf(await rootBundle.load("assets/xx.ttf")),
    );
    final Document pdf = Document(
      author: "xx",
      keywords: "xx",
      creator: "xx",
      title: "xx: $dbName",
      subject: "xx",
      theme: myTheme,
    );

**Comment by moovida** [comment]
Hi @skylning , thanks for this. 
I was thinking that we could add one default theme with unicode support? Could you advise me here? Could you choose a free licensed font that could be used? I could then add the above fix you propose.
Would you also have a project (database) that I could use to test the export?

**Comment by moovida** [comment]
Hi @skylning , I have adopted your suggestions and added Open-Sans the SMASH assets to test it. It works nicely.

So one thing to do now is to choose a good font to cover as much as possible. Do you have something in mind? Another option would be to add a couple of them and add a setting to let the user select.
I am not big font expert, so some suggestion would come in handly.

**Comment by skylning** [comment]
I am not big font expert too @moovida 
and i find the font is somebody shared on internet to fit my language
