### ISSUE TITLE
Unable to build an APK

### ISSUE THREAD

**Issue by mbasa** [moovida/smash#86]
I have been trying to build an APK from the `master` branch using the latest Flutter (I can send a flutter doctor if requested), but am having errors. I think the possible reasons might be are: 

* The gradle version set in build.gradle is set too high since the normal version is 3.5.0
* There might be incompatibilities with the dependencies. For example:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/mbasa/Development/AndroidStudioProjects/smash/build/file_picker/intermediates/library_manifest/debug/AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.
```

Will really appreciate it if the build process/environment can be outlined so that we can build our own APKs. Thanks!

**Comment by moovida** [comment]
Hi, we are building with the flutter dev channel. Can you try to set that one?

**Comment by mbasa** [comment]
> Hi, we are building with the flutter dev channel. Can you try to set that one?

I am also using the dev channel. Thanks. 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.25.0-8.0.pre, on Mac OS X 10.13.6 17G14042
    darwin-x64, locale en-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
```

**Comment by moovida** [comment]
Why do you think gradle is too high? You will need the one set in the project. I remember the <queries> issue being linked to gradle. And it took me some time to solve.

**Comment by mbasa** [comment]
I always get the following error when the gradle version is set to 4.0.2. Version 3.5.0 gradle version seems to be the default when creating a new flutter project.  

```
* What went wrong:                                                      
Execution failed for task ':app:stripDebugDebugSymbols'.                
> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 20.0.5594570, 21.3.6528147, 22.0.7026061
```

**Comment by moovida** [comment]
I am quite sure version 4 is necessary to make this work. Can you try to download an updated version of the NDK and see if that works?

**Comment by mbasa** [comment]
Ok. Downloaded and added NDK 21.0.6113669 and it compiled cleanly. Thanks.
