### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by skylning** [moovida/smash#87]
when i get the latest source code and build it,i get 2 errors as follow :
lib/eu/hydrologis/smash/export/pdf_export.dart:251:27: Error: Cannot invoke a non-'const' factory where a const expression is expected.
Try using a constructor or factory that is 'const'.
                  border: BoxBorder(
                          ^^^^^^^^^
/D:/flutter/.pub-cache/git/extended_image-6e431b3095f374ec0ff317c7016f495bc75a07b9/lib/src/extended_image.dart:785:32: Error: Method not found: 'MediaQuery.maybeOf'.
    _invertColors = MediaQuery.maybeOf(context)?.invertColors ??
                               ^^^^^^^

FAILURE: Build failed with an exception.

**Comment by moovida** [comment]
Hi @skylning , I finally managed to fix it. I had some build issues first due to the background_locator dependency.

but build should now work again as of commit: 618216a

Let me know if it works for you.

**Comment by skylning** [comment]
Tanks moovida,it woks for me now




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andrea Antonello"<notifications@github.com&gt;; 
发送时间: 2020年12月23日(星期三) 下午3:59
收件人: "moovida/smash"<smash@noreply.github.com&gt;; 
抄送: "防火墙"<75968655@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [moovida/smash] Build error  (#87)





 
Hi @skylning , I finally managed to fix it. I had some build issues first due to the background_locator dependency.
 
but build should now work again as of commit: 618216a
 
Let me know if it works for you.
