### ISSUE TITLE
Note feature: default text

### ISSUE THREAD

**Issue by sabas** [moovida/smash#88]
I had my first trip logged with smash, although it wasn't a field survey.
When creating a note I noticed that I need multiple taps to add an entry, so I was wondering if in the note properties panel we could simplify by clicing on the text field (instead of only on the pencil, and remove the default text (perhaps leaving "Note" in italics, which goes away as soon as I enter the edit mode)

**Comment by moovida** [comment]
Thanks for the input, I like the idea and agree that saving time is mandatory on the field.

**Comment by moovida** [comment]
This is now done as you described it. I also tried to find a quick way to end editing, but with gestures too much uncertainty is coming in. 
So to finish you still will have to push the save button :-)

**Comment by sabas** [comment]
Grazie Andrea :+1:

**Comment by moovida** [comment]
Can I ask you if you are able to access the google play beta program? The new release candidate is released as beta on the store and anyone should be able to access it.

**Comment by sabas** [comment]
@moovida  yes I've joined now, I'm waiting for the signup sucess..

**Comment by moovida** [comment]
@sabas great, thank you. Can you tell me what you needed to do. I have not been able to check with my email, since being my developer email it already figured. 

Does it take much time to do so?

Thanks

**Comment by sabas** [comment]
There's only a Beta paragraph on the market page with a Learn more or Join link. When pressing join you enroll in the program. (but I don't know if you have to confirm me or nor)

**Comment by moovida** [comment]
Let me check, I thought I would not need to confirm you, I left it open.

**Comment by moovida** [comment]
Ok, checked. No need for me to do anything.
