### ISSUE TITLE
No apk-File under "Assets" for Version 1.6.2.

### ISSUE THREAD

**Issue by IeP4nieF** [moovida/smash#93]
Could you please offer an apk-File under Assets also for Version 1.6.2.? Der is only a zip- and a tgz-File.

Thanks!

**Comment by moovida** [comment]
@IeP4nieF , I apologize for the huge delay. For some technical reasons I have not been able to this quickly.

In the meanwhile 1.6.3 is out, and there I took care to place the apk. I hope that is fine. Cheers
