### ISSUE TITLE
Issue on Linux (Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by shujaatak** [moovida/smash#99]
SMASH doesn't get past this stage, It stucks at **Loading Workspace**:
![linux](https://user-images.githubusercontent.com/14161646/106588714-f539a080-656c-11eb-8f56-5d6c30017b7c.png)

**Comment by moovida** [comment]
hah, I currently have no access to my linux box (and won't in days) so you will need to do some checking here. 
In the past I have used the SMASH export and even wanted to do a release. But then some changes in the flutter devel channel made me refrain. 

I am currently using the macos version for all my debugs that allow it. So I might help you. I assume you are launching it from the devel environment, so do you see any particular error?

**Comment by shujaatak** [comment]
Found this error:
`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (libsqlite3.so: cannot open shared object file: No such file or directory)`

**Comment by moovida** [comment]
Ahhh, now I see. Ok, for linux sqlite is not shipped by the sqlite package. Look here: https://pub.dev/packages/sqlite3

Find the note about linux and see what package needs to be installed. It will pull the system sqlite3 lib

**Comment by shujaatak** [comment]
Used this and it solved the issue:
`sudo apt install libsqlite3-dev`

**Comment by moovida** [comment]
Mind that the desktop versions are in very early stage. Most things do work, but you might find some that are dedicated to mobile and should not be there on desktop. If you want to open issues for those, please make the issue with the desktop label. I will sure try to address them when I have time to.
